# Generated by Django 2.2.5 on 2019-10-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
    ]
